### ISSUE TITLE
Missing icons for Redmine v3.4

### ISSUE THREAD

**Issue by iquiw** [akabekobeko/redmine-theme-minimalflat2#108]
As far as I can find, the following icons are missing in minimalflat2 when using Redmine v3.4.

* `icon-add-bullet` - used for "Search for watchers to add" in new issue
* `icon-close`      - used for delete icon in My page
* `icon-comments`   - used for reply message in forum
* `icon-download`   - used for download icon of attachment
* `icon-locked`     - used for locked message in forum
* `icon-news`       - used for "Latest news" in project overview
* `icon-shared`     - used for shared version in sub project setting
* `icon-sticky`     - used for sticky message in forum

Please let me know if you want to have more information.

**Comment by akabekobeko** [comment]
@iquiw 

I fixed this issue with minimalflat2 v1.3.1, please close the issue unless you try it.

**Comment by iquiw** [comment]
Thank you!

I have one wish about `icon-download`.
Could you consider to use some different icon for `icon-download` from arrow down?
For example, `download3` icon (e902) of IcoMoon, or `download` icon of Entypo.

If you don't like the change, feel free to close this 😄

**Comment by akabekobeko** [comment]
Since v1.3.1 has already been released.
I will respond to any other fixes in the next version as well.

I registered an issue as #110 so as not to forget the fix.
If there are other icons to change, please add an issue. I will close this issue.

**Comment by iquiw** [comment]
Thank you again!
