### ISSUE TITLE
Change the download icon to `Entypo+` icon

### ISSUE THREAD

**Issue by akabekobeko** [akabekobeko/redmine-theme-minimalflat2#110]
Request of #108.

**Comment by iquiw** [comment]
Download icon of Default theme seems changed in v4.0.0.
[More neutral color download icon](http://www.redmine.org/issues/26577)

Just for reference.

**Comment by akabekobeko** [comment]
@iquiw 

The new icon looks like the download icon for `Entypo +`. Therefore, I will replace this icon.

**Comment by akabekobeko** [comment]
@iquiw 
I changed the icon with `minimalflat2` v1.3.2.
Please check and close the issue if there is no problem.

**Comment by iquiw** [comment]
It''s fine, thank you.

I cannot close this issue since I did not open it.

**Comment by akabekobeko** [comment]
Sorry I did not notice. It closed by me.
