### ISSUE TITLE
When "my project" is displayed in 1 column mode, the table protrudes

### ISSUE THREAD

**Issue by akabekobeko** [akabekobeko/redmine-theme-minimalflat2#117]
When "my project" is displayed in 1 column mode, the table protrudes (from #115).

> it works: now is responsive. The only mistake is that the widget on the right, when I access the site from mobile device, go out the border of his container.
> I attach here the screenshot of the issue in action (1) and the screenshot of the widget as it appears on pc device.

![](https://user-images.githubusercontent.com/813690/30112398-8ad4f626-9311-11e7-99ac-c832978296de.png)

![](https://user-images.githubusercontent.com/813690/30112399-8d4c0f16-9311-11e7-894c-4bdfe0742a8c.png)

**Comment by akabekobeko** [comment]
note:

The calendar widget is displayed even if the table protrudes in a theme of default. Improvement is difficult because it is caused by fixed width.

**Comment by akabekobeko** [comment]
This problem does not occur in the standard theme because body has `font-size: 12px` specified. In other words, it does not address folding as CSS. Because it is small, I just happen to display it.

minimalflat2 does not specify `font-size` for body, it is a policy to display the character size according to the environment of the end user. I do not want to change the policy to fix this issue.

**Comment by akabekobeko** [comment]
@pasqualedante 

To fix this issue you need to reduce the `font-size` of body or table. However, if it is reduced with a fixed value, the unit will be displayed small with a large display, even em.

The design policy of minimalflat2 is to not fix `font-size` as much as possible. This is a policy to obtain optimal display on many displays.

Therefore we decided not to correspond to this issue. If the display of table overflows, please respond by reducing the character size of the Web browser or partially specifying it with User CSS (Stylish, and others).

If there are any other good ideas, please comment. The close of the issue will be judged after reading your comment.

**Comment by akabekobeko** [comment]
It is likely to be fixed without changing `font-size`. Will use `theme.js` to make it like the issues table of **My Page**.

```html
<div class = "autoscroll">
  <table>
  </table>
</div>
```

In this way you can use the scroll bar if it can not be displayed.

**Comment by akabekobeko** [comment]
@pasqualedante

I fixed it with minimalflat2 v1.3.5. Please check it.

**Comment by pasqualedante** [comment]
@akabekobeko 
yes now it works. Thanks for the fix!
