### ISSUE TITLE
worktime font size

### ISSUE THREAD

**Issue by kaisaintz** [akabekobeko/redmine-theme-minimalflat2#126]
in the redmine3.4.4.when use the plugin Redmine Work Time plugin(http://www.redmine.org/plugins/redmine_work_time),the font size is too large

<img width="1060" alt="20180129204044" src="https://user-images.githubusercontent.com/16593547/35510900-ed50dcda-0534-11e8-829e-9028a2dcc79a.png">

**Comment by akabekobeko** [comment]
I am sorry for the delay in reply. Basically, this theme does not correspond to a specific plugin.

I think that the plug-in itself holds the appearance of the plug-in. `font-size` may be changed in the Redmine default theme as well.

Therefore it would be safe for the plug-in side to preserve its appearance by specifying `!important` on the CSS.
