### ISSUE TITLE
Bigger collapse/expand buttons on the Projects page

### ISSUE THREAD

**Issue by dnyamy** [akabekobeko/redmine-theme-minimalflat2#139]
Hello all, 
These days I have been discovering this theme that matches my need so well. Thanks a lot for sharing. 

I appreciate especially the possibility to collapse/expand projects on the Projects page. However, I have noticed that navigation is not that easy on mobile devices. It is a real challenge, with a finger, to click exactly the +/- buttons. I almost always end opening the project, instead of just expanding it. 

Please could someone give me a nudge on how to make those button bigger ? 

Thanks in advance
Dorice

**Comment by akabekobeko** [comment]
Sorry for the late reply.

Project collapse / expand can be toggled by clicking on the entire header, not just the plus / minus icon. The icon is for displaying a hint of the expanded state.

The header is displayed to the full width of the content and is sufficient as an operation area. Therefore, this issue will be closed.
