### ISSUE TITLE
Alphabetical pagination on project page

### ISSUE THREAD

**Issue by dnyamy** [akabekobeko/redmine-theme-minimalflat2#141]
Hello,

I have been using this nice theme for some few month now.
But we have many projects (we will reach thousands), and hierachization won't be sufficient for quick navigation. 
So I am considering alphabetical pagination of the subprojects of each project.

Please could someone give me a nudge on how to make this ?

Thanks in advance

Dorice

**Comment by akabekobeko** [comment]
@dnyamy The Redmine theme can be operated only on the client side. So you will implement a pseudo page nation with DOM manipulation with `application.js`.

However, if the cause of the performance problem is the DOM of a huge number of projects, "pseudo" pagination can not solve it.

In other words, "pseudo" is a way to display only the necessary items by `display: none` DOM in CSS. In real pagination, the generation of DOM itself is the minimum required.

**Comment by akabekobeko** [comment]
Performance seems to be achieved only by DOM operation if you want to improve navigation without any problems.

To do that, customize `src / assets / javascripts / theme.js` of this theme.
