### ISSUE TITLE
改行のみの行が広く表示される

### ISSUE THREAD

**Issue by Pon57** [akabekobeko/redmine-theme-minimalflat2#147]
利用させていただいております。ありがとうございます。
タイトルの通り改行のみの行が広く表示されてしまいます。
チケットの説明、注記、Wiki等で確認しています。
仕様でないのであれば、文字一行分の空行としていただくことは可能でしょうか？
よろしくお願いします。

環境はLightsailにUbuntu18.04のインスタンスを作り、その中でApache+PassengerにてRedmine4.0.2を動かしています。

**Comment by akabekobeko** [comment]
現在の Wiki などにおける段落は

```css
.wiki p {
  margin: 2em 1em;
}
```

としています。これは段落間を遠目に視認しやすくするための意図的な値です。margin の上下を `2em` から `1em` にすれば段落の間隔は狭くなりますが、本テーマとしては現在の値を仕様としておきます。

もし @Pon57 さんの環境でだけ狭めるのであれば

* テーマの `application.css` からテキスト エディター `.wiki p` を検索して値を調整する
* Web ブラウザーのユーザー スタイルシートで Redmine サイトに対して `.wiki p` を好みの値により上書きする

などの方法が考えられます。

**Comment by akabekobeko** [comment]
本件は仕様ですので close します。修正を望まれる場合はお手数ですが前述のコメントにある CSS をご自身で変更してください。

**Comment by Pon57** [comment]
すみません、返信に気が付かずすっかり忘れておりクローズできていませんでした。
ありがとうございました！ @akabekobeko
