### ISSUE TITLE
Tooltip texts are invisible by click on Gantt chart

### ISSUE THREAD

**Issue by iquiw** [akabekobeko/redmine-theme-minimalflat2#148]
Tooltip texts on Gantt chart become invisible when clicking on the bar.

Without click
![image](https://user-images.githubusercontent.com/238681/57425045-be7a0d80-7254-11e9-9759-e2fc392e58e1.png)

With clicked
![image](https://user-images.githubusercontent.com/238681/57423348-9c7d8c80-724e-11e9-811b-8673e21d2f01.png)

Redmine: 4.0.3
Minimalflat2: 1.5.0
Browser: Chrome and Firefox

**Comment by akabekobeko** [comment]
@iquiw Color specification was missing in the CSS of Redmine v4.0. It will be fixed in minimalflat2 v1.6.0, so please check once it is released.

**Comment by iquiw** [comment]
Works fine. Thank you!
