### ISSUE TITLE
Duplicate question mark

### ISSUE THREAD

**Issue by pva** [akabekobeko/redmine-theme-minimalflat2#151]
After enabling theme I see duplicate question marks at the heading:
![Снимок экрана от 2019-05-20 18-15-42](https://user-images.githubusercontent.com/92356/58032477-53b9b380-7b2b-11e9-86b9-5aeeb16f766f.png)

**Comment by akabekobeko** [comment]
Sorry, from the viewpoint of verification environment and development cost, this theme basically does not support plugin-specific problems.
