### ISSUE TITLE
Issue links on Gantt are not clickable with Redmine v4.0.4

### ISSUE THREAD

**Issue by iquiw** [akabekobeko/redmine-theme-minimalflat2#152]
With Redmine v4.0.3,

![image](https://user-images.githubusercontent.com/238681/59326690-48b90400-8d22-11e9-8b8c-04ab1ccb18a4.png)

With Redmine v4.0.4, issue link is not clickable. Right click menu on the issue is also not available.

![image](https://user-images.githubusercontent.com/238681/59326682-3d65d880-8d22-11e9-8c24-5cea15ce1484.png)

The following change might be related.
[Defect #31268: Fix gaps in resizable gantt chart - Redmine](http://www.redmine.org/issues/31268)

Redmine: 4.0.4
Minimalflat2: 1.6.0
Browser: Chrome and Firefox

**Comment by akabekobeko** [comment]
It was checked that this issue was also corrected by #153.

**Comment by akabekobeko** [comment]
@iquiw Released v1.6.1, which fixes this issue. Please check that the problem has been fixed.

**Comment by iquiw** [comment]
@akabekobeko Thanks! Works fine.
