### ISSUE TITLE
minimalflat not showing in themes list

### ISSUE THREAD

**Issue by shanedobson-ibboost** [akabekobeko/redmine-theme-minimalflat2#155]
I've just tried to install this theme but it's not working. 

I've got a new Redmine 4.0.4 install running on CentOS 7. I installed a few themes just now, and all the others showed up in the options list to choose from, but this one did not. 

I followed the same process for all themes:

- download the master zip
- unzip to public/themes/minimalflat at Redmine directory (or other theme folders for other ones)
- ensure permissions for folder are correct
- restart Redmine services
- in the UI, go to Administration > Settings > Display. There are many options but this one is not one of them. 

I can also access all themes from my own profile page, and it's the same - all appear except this one.

**Comment by n0nel** [comment]
Let's read the "Installation".
Go to the "releases" page, then you will download minimalflat2-*.zip.

**Comment by akabekobeko** [comment]
@n0nel Thank you!

@shanedobson-ibboost 
Although it has already been commented, the distribution version of this theme will be ZIP on the Releases page.

- [Releases - akabekobeko/redmine-theme-minimalflat2](https://github.com/akabekobeko/redmine-theme-minimalflat2/releases)
