### ISSUE TITLE
gantt chart not work 4.1.0

### ISSUE THREAD

**Issue by u2fuji** [akabekobeko/redmine-theme-minimalflat2#157]
テンプレートを使わせていただいています。
先日、Redmineを4.1.0にアップデートしたところ、ガントチャートが正常に表示されなくなってしまいました。
具体的には、ガントチャートのグラフが全く表示されなくなりました。
（チケット一覧や、右クリックメニューは表示されます）

ブラウザキャッシュの削除等は、実施してますが、状況変わらずでした。
テンプレートを別のものに切り替えて試すと、正常にガントチャートは表示される状況です。

デザイン的に気に入っているので、出来れば使い続けたいので、確認していただけると大変助かります。

**Comment by akabekobeko** [comment]
Redmine v4.1 で HTML/CSS が大幅に変更されたようで、本件もその影響による問題でした。minimalflat2 v1.7.0 にて Redmine v4.1 対応をおこない、あわせて本件も修正されたと思われますのでご確認ください。

- [Release v1.7.0 · akabekobeko/redmine-theme-minimalflat2](https://github.com/akabekobeko/redmine-theme-minimalflat2/releases/tag/v1.7.0)

もし問題がある場合は、お手数ですが改めて issue 登録をお願いします。

**Comment by u2fuji** [comment]
ご対応ありがとうございます。
無事、ガントチャートが表示されるようになりました。
