### ISSUE TITLE
Custom favicon

### ISSUE THREAD

**Issue by dnyamy** [akabekobeko/redmine-theme-minimalflat2#178]
Hello,
First of all, thank you very much for this nice theme.

I have tried to rather use my custom favicon. To do so, I have updated the files in src/assets/favicon and rebuilt the package. But I am still getting the rocket. 

Please I am very new to JS. What am I missing ?

Thanks in advance
Regards
Dn

**Comment by akabekobeko** [comment]
@dnyamy 
The `src/assets/favicon` directory is for developers, so please download and extract the ZIP (e.g. `minimalflat2-1.8.1.zip`) file from the [release page](https://github.com/akabekobeko/redmine-theme-minimalflat2/releases), not the Git repository.

If you want to change Favicon, replace `favicon/favicon.ico`.

**Comment by dnyamy** [comment]
Hello,
It worked.
Thanks a lot
Regards
Dn
