### ISSUE TITLE
Responsive view

### ISSUE THREAD

**Issue by lumilo8** [akabekobeko/redmine-theme-minimalflat2#58]
Hi, we love this theme, thanks! However, the responsive view isn't available yet, right?

**Comment by akabekobeko** [comment]
Responsive view is a feature from the Redmine 3.2, what is your Redmine version 3.2 or higher?

**Comment by akabekobeko** [comment]
Describing it responsive layout is Redmine 3.2 or later README.

**Comment by akabekobeko** [comment]
Favicon ( v2.5 or later ) and also describes to the README for similarly responsive view.

**Comment by akabekobeko** [comment]
Responsive layout support has noted that it is a Redmine 3.2 or later.
If the case in Redmine 3.2 or later responsive view is invalid, please reopen the issue.

**Comment by lumilo8** [comment]
Wow, thanks! Great job.
