### ISSUE TITLE
letter-spacing normal is better for displaying

### ISSUE THREAD

**Issue by LeGiangAnh** [akabekobeko/redmine-theme-minimalflat2#59]
Hi,

I really like your template. I'd like to share some suggestions below:
 -  If you us letter-spacing: normal for body, it will have a better looking
 -  The header padding is 0.5em and cause a wasted spaces. It will be better if we use 0: https://goo.gl/fYJs7W

**Comment by akabekobeko** [comment]
> If you us letter-spacing: normal for body, it will have a better looking

* The current letter-spacing is my favorite
* But it may be too wide, and then change the order from 0.09em to 0.07em

> The header padding is 0.5em and cause a wasted spaces. It will be better if we use 0

* Padding since it is sufficient margin to delete
* Support in the next version

**Comment by akabekobeko** [comment]
It added support for the request. The changes are applied to the v1.1.2.
