### ISSUE TITLE
Left sidebar support?

### ISSUE THREAD

**Issue by LeGiangAnh** [akabekobeko/redmine-theme-minimalflat2#62]
Hi @akabekobeko ,

Do you have the plan to add a left sidebar to the theme like this:
http://www.keenthemes.com/preview/metronic/
http://www.keenthemes.com/preview/metronic/theme/admin_1/
It could save a lot of space and improve the productivity.

Thanks.

**Comment by akabekobeko** [comment]
If support the required correspondence, such that the `sidebar` and `main` to `position:absolute`.
Is the problem DOM structure of Redmine also be maintained in the future.

**Comment by LeGiangAnh** [comment]
Thank you. I saw some new Redmine theme also has that bar since the high res monitor is more and more popular.
I'm using 4K monintor at the moment and the default view (with out sidebard) is very large and there are many redundant spaces.

**Comment by akabekobeko** [comment]
@LeGiangAnh

Sorry, left sidebar of support is difficult.
Future Redmine theme will re-examine can also define the HTML DOM.
