### ISSUE TITLE
Missing images/loading.gif

### ISSUE THREAD

**Issue by silentw** [akabekobeko/redmine-theme-minimalflat2#65]
![images/loading.gif](http://i.imgur.com/72EzO1Z.png)

References:
`#ajax-indicator span{background-position:0% 40%;background-repeat:no-repeat;background-image:url("../images/loading.gif");padding-left:26px;vertical-align:bottom}`

`input.autocomplete.ajax-loading{background-image:url("../images/loading.gif")}`

**Comment by silentw** [comment]
Solution:
Copy `/images/loading.gif` to `/public/themes/minimalflat2/images/loading.gif`

**Comment by akabekobeko** [comment]
There are places that reference images to other ( draft.png, openid-bg.gif, ...etc ). All be modified to copy.

**Comment by akabekobeko** [comment]
Thank you for the report.
Fix a reference to the images, Please make sure because it is supported by v1.1.4.
