### ISSUE TITLE
Login form Not fit in mobile view

### ISSUE THREAD

**Issue by akiya64** [akabekobeko/redmine-theme-minimalflat2#68]
UserName/Password area overflow.
Login button display a part.

Login form seems rendering for 320x480px.
Reproduce in Firefox responsive view , 320x480px

<img src="https://cloud.githubusercontent.com/assets/14228487/14190626/c4a5a420-f7ce-11e5-8b08-2171bf5dbf17.jpg" width="320" heght="auto" alt="login form">

My Enviroment
- Android 5.1
- Chrome 49.0 / Firefox 45.1 for Android
- Display size 720x1280px

**Comment by akabekobeko** [comment]
Fix the this bug, Please check with v1.1.5.

**Comment by akiya64** [comment]
I have updated v1.1.5 , and checked textbox/button within the screen.
Tahnks for fix speedy.
