### ISSUE TITLE
DMSF Icon showing multiple times

### ISSUE THREAD

**Issue by DX-Nkumar** [akabekobeko/redmine-theme-minimalflat2#71]
Using DMSF for document management system but when I use minimal flat theme, icons started showing multiple times.
![dmsf_issuee](https://cloud.githubusercontent.com/assets/8734378/16220616/889877c4-37ab-11e6-9788-be580b1b9360.png)

**Comment by akabekobeko** [comment]
@DX-Nkumar 

Fix a this bug.
Please check with minimalflat2 v1.2.0 and Redmine v3.3.
