### ISSUE TITLE
Right sidebar is too large in 4K monitor

### ISSUE THREAD

**Issue by LeGiangAnh** [akabekobeko/redmine-theme-minimalflat2#74]
Hi,

In my 4K monitor, the right sidebar is very large and waste:
![image](https://cloud.githubusercontent.com/assets/5027251/16921680/ac90214e-4d3c-11e6-901a-6e768f3e459e.png)

Thanks.

**Comment by akabekobeko** [comment]
@LeGiangAnh 

The current sidebar style is almost with Redmine of the default theme. Can't change the DOM of HTML in Redmine theme in the Non-JavaScript methods.

Also, if change in the JavaScript it might be compatibility problems (In a future version).
Therefore, it is difficult to support this issue.

Please comment if there are any good ideas. I want to close this issue if it is not there.
