### ISSUE TITLE
Icons for other popular plugins?

### ISSUE THREAD

**Issue by LeGiangAnh** [akabekobeko/redmine-theme-minimalflat2#76]
Hi,

Is it possible to add the icons for other popular plugin like Redmine People, Redmine CRM?

![image](https://cloud.githubusercontent.com/assets/5027251/16938302/76a3e8f4-4da0-11e6-9c7d-522fede25fc5.png)

Thanks,
Anh

**Comment by akabekobeko** [comment]
memo:

* To support as much as possible if there is a request
* However, those that do not work with the latest of Redmine are too old are excluded
* [People - Plugins - Redmine](http://www.redmine.org/plugins/redmine_people)
* [RedmineCRM - Premium Redmine plugins, CRM, Helpdesk, Invoices](https://www.redminecrm.com/)

**Comment by akabekobeko** [comment]
Relation #78

**Comment by akabekobeko** [comment]
Become 500 error when you start the Redmine 3.3 to install the [People](http://www.redmine.org/plugins/redmine_people) and [Redmine CRM](https://www.redminecrm.com/projects/crm/pages/1).

```
Processing by WelcomeController#index as HTML
  Current user: admin (id=1)
Completed 500 Internal Server Error in 100ms (ActiveRecord: 23.3ms)

ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "contacts_settings" does not exist
LINE 5:                WHERE a.attrelid = '"contacts_settings"'::reg...
                                          ^
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
                FROM pg_attribute a LEFT JOIN pg_attrdef d
                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
               WHERE a.attrelid = '"contacts_settings"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum
):
  plugins/redmine_contacts/app/models/contacts_setting.rb:59:in `check_cache'
  plugins/redmine_contacts/lib/redmine_contacts/patches/application_controller_patch.rb:34:in `user_setup_with_contacts'
```

These compatibility has become to Redmine 3.2.
Therefore support is give up. It might again supported in the future.

**Comment by akabekobeko** [comment]
Supported on successful installation. Other plug-ins will support as well.

Please create issues individually if you wish.
