### ISSUE TITLE
Suggestion - Option to hide closed versions

### ISSUE THREAD

**Issue by LeGiangAnh** [akabekobeko/redmine-theme-minimalflat2#83]
Hi,

I'd like to suggest to have the option to hide closed versions in Settings. I have 100+ versions there and the list is very long.

Thanks,
Anh

**Comment by akabekobeko** [comment]
@LeGiangAnh 

`version` was to `close` in the `Roadmap` will be to change the display in the "Show completed versions". `version` of this checkbox is `close` if `off` will not be displayed.

![ss-01](https://cloud.githubusercontent.com/assets/1257526/18654489/5706e7aa-7f1c-11e6-9473-381387795838.png)

If You talk about another screen, please again comment.

**Comment by LeGiangAnh** [comment]
Hi. Yes, I'd like to hide closed version in Setting. There was an option to do that in Roadmap already.

**Comment by akabekobeko** [comment]
@LeGiangAnh 

What resolve this issue in this option setting ("Show completed versions")? Or, do you have another a problem?

If it resolved to a close this issue.
