### ISSUE TITLE
/trackers and /issue_statuses couldn't sort

### ISSUE THREAD

**Issue by murat-to** [akabekobeko/redmine-theme-minimalflat2#86]
At /trackers page and /issue_statuses page.
I couldn't sort row.

element span, class sort-handle ui-sortable-handle is not visible?

browser: chrome

please correspond.

**Comment by murat-to** [comment]
管理画面のトラッカーページで、トラッカーの並べ替えができません。
デフォルトテーマだと表示されている並べ替え用の要素が表示されていない様です。

ご多忙中の事とは存じますが、ご対応頂ければありがたく存じます。

以上、失礼致します。

**Comment by akabekobeko** [comment]
この問題はおそらく #75 で解決されると思われます。このプロジェクト、しばらく放置していましたが v1.2.2 を来週あたりリリースして #75 などの修正を反映させます。

**Comment by murat-to** [comment]
既出確認を怠りました。
申し訳ありません、ご容赦を。<(_ _)>
お恥ずかしい限りです。///

**Comment by akabekobeko** [comment]
こちらこそリリースを保留していて申し訳ありませんでした。
半端な状態で放置するのではなく、修正したものに関してはリリースにより反映しておくべきでした。

今週末までには v1.2.2 としてリリース予定ですので、もう少しお待ちください。

**Comment by akabekobeko** [comment]
@murat-to 

v1.2.2 をリリースしたので本件が修正されているかご確認ください。
もし問題なければ issue を close してください。

**Comment by murat-to** [comment]
@akabekobeko 
ありがとうございます！問題なく使えております。<(_ _)>
