### ISSUE TITLE
Not showing CSS style after install 

### ISSUE THREAD

**Issue by hamedhpajouh** [akabekobeko/redmine-theme-minimalflat2#89]
Hello, 

I installed the latest theme on my Redmine 3.3.1 environment but the style doesn't look well. for instance my project jump list not working at all

**Comment by akabekobeko** [comment]
@HNSX 

I tried it with Redmine 3.3.1 but it works normally, please check the following about your environment.

* Install themes in `REDMINE_ROOT/public/themes/minimalflat2`
* This theme's folder permissions the same as other themes
* Restart Redmine after installing the theme
* Run super reload of Web Browser (Clear caches)
* Configuration of yhe http server (Apache, nginx, ...etc)
