### ISSUE TITLE
Version color visibility in gantt

### ISSUE THREAD

**Issue by iquiw** [akabekobeko/redmine-theme-minimalflat2#92]
First of all, thank you for the nice theme!

The problem is that version lines are rendered with white color in gantt, which is hard to be recognized.
Also, the end marker is not visible.
![minimalflat2](https://cloud.githubusercontent.com/assets/238681/23491465/d8558064-ff41-11e6-830c-6c3df48ca881.png)

Here is the same gantt with Default theme.
![defaulttheme](https://cloud.githubusercontent.com/assets/238681/23491544/3b65842e-ff42-11e6-8f25-1c8f558a45e8.png)

**Comment by akabekobeko** [comment]
Thanks for the report. I fixed the problem.

![ss-01](https://cloud.githubusercontent.com/assets/1257526/23576392/635cdf26-00e7-11e7-8b8d-43822d71e904.png)

**Comment by iquiw** [comment]
Thank you!
